name: Run Server Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server
    
    env:
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      
      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
